import "./globals.css";
import SessionProviderWrapper from "@/providers/SessionProviderWrapper";


export const metadata = {
  title: "Adult",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='dark'>
      <body>
        <SessionProviderWrapper>
          {children}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
